server {
    listen 8080;
    server_name *.radiocombinator.com;

    # Redirect HTTP to HTTPS (Cloudflare's HTTPS)
    if ($http_x_forwarded_proto = "http") {
        return 301 https://$host$request_uri;
    }

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}