server {
    listen 8080;
    server_name *.radiocombinator.com;

    # Redirect HTTP to HTTPS (Cloudflare's HTTPS)
    if ($http_x_forwarded_proto = "http") {
        return 301 https://$host$request_uri;
    }

    root /usr/share/nginx/html;
    index index.html;

    etag on;
    if_modified_since exact;

    # HTML → always revalidate
    location ~* \.html$ {
        add_header Cache-Control "public, no-cache, must-revalidate";
    }

    location ~* \.(js|css)$ {
        add_header Cache-Control "public, must-revalidate";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}